### ISSUE TITLE
✨ [feat] 장터 좋아요 및 검색 기능 구현

### ISSUE THREAD

**Issue by rossssa** [CapstoneDavinchi/Capstone_Back#56]
## Description
장터 좋아요/좋아요 취소 구현
장터 게시글 검색 기능 구현
내가 찜한 장터 게시글 조회 기능 구현

## To-do
- [x] 장터 좋아요/좋아요 취소 구현
- [x] 장터 게시글 검색 기능 구현
- [x] 내가 찜한 장터 게시글 조회 기능 구현
- [x] Swagger 추가
